# -*- coding: utf-8 -*-
"""Pandas_Profiling_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oN_NL-PQ8M5F4TQB8R0IoFxb27fKnqGw
"""

import pandas as pd

df=pd.read_csv('/content/tested.csv')

pip install ydata-profiling

from ydata_profiling import ProfileReport
prof=ProfileReport(df)
prof.to_file(output_file='output.html')